diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
credential.helper=manager-core
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filesystem.Oracle Corporation|1.8.0_191|-419601078.timestampresolution=1001 mıcroseconds
filesystem.Oracle Corporation|1.8.0_191|-419601078.minracythreshold=0 nanoseconds
user.name=HamitM
user.email=hamitmizrak@gmail.com
core.editor=notepad++
alias.harita=log --all --graph --decorate --oneline
merge.tool=p4merge
diff.tool=p4merge
filesystem.Oracle Corporation|1.8.0_261|-419601078.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_261|-419601078.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/hamitmizrak/Angular_SpringBoot.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
